CREATE TABLE ALERTA_DENGUE (
    DataInicioSemanaEpidemiologicDaTimestamp BIGINT NOT NULL,
    SemanaEpidemiologica INT NOT NULL,
    CasosEstimados DOUBLE NOT NULL,
    CasosEstimadosMinimo DOUBLE NOT NULL,
    CasosEstimadosMaximo DOUBLE NOT NULL,
    CasosNotificados INT NOT NULL,
    ProbabilidadeTransmissao DOUBLE NOT NULL,
    IncidenciaPor100kHabitantes DOUBLE NOT NULL,
    CodigoLocalidade INT NOT NULL,
    NivelRisco INT NOT NULL,
    Identificador BIGINT PRIMARY KEY,
    VersaoModelo VARCHAR(255) NOT NULL,
    Mensagem TEXT NULL,
    TaxaTransmissao DOUBLE NOT NULL,
    Populacao DOUBLE NOT NULL,
    TemperaturaMinima DOUBLE NULL,
    UmidadeMaxima DOUBLE NULL,
    AreaReceptiva INT NOT NULL,
    AreaTransmissao INT NOT NULL,
    NivelIncidencia INT NOT NULL,
    UmidadeMedia DOUBLE NULL,
    UmidadeMinima DOUBLE NULL,
    TemperaturaMedia DOUBLE NULL,
    TemperaturaMaxima DOUBLE NULL,
    CasosProvaveis INT NOT NULL,
    CasosProvaveisEstimados DOUBLE NULL,
    CasosProvaveisEstimadosMinimo DOUBLE NULL,
    CasosProvaveisEstimadosMaximo DOUBLE NULL,
    CasosConfirmados INT NULL,
    NotificacoesAcumuladasAno INT NOT NULL
);

CREATE INDEX IX_ALERTA_DENGUE_SemanaAno ON ALERTA_DENGUE (SemanaEpidemiologica);
