name: Testes Unitários

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'
    
    - name: Restaurar dependências
      run: dotnet restore
      
    - name: Compilar
      run: dotnet build --configuration Release --no-restore
      
    - name: Executar testes
      run: dotnet test --configuration Release --no-build --verbosity normal
